name: model_paintings
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      
      - name: Unzip data set
        #env:
          #REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          unzip dataset.zip 
      
      - name: install requirements
        #env:
          #REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
        
        
      - name: Train model
        #env:
          #REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            python paintings_classification.py 
          
          
      - name: Reports
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            cat reports.txt >> results.md
            echo >> results.md
            cml-publish confusion_matrix.png --md --title 'confusion-matrix' >> results.md
            cml-publish accuracy_loss.png --md --title 'accuracy_loss' >> results.md
            cml-send-comment results.md

