name: model_paintings
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      
      - name: Unzip data set
        run: |
          unzip dataset.zip 
      
      - name: install requirements
        run: |
          pip install -r requirements.txt
        
        
      - name: Train model
        run: |
            python paintings_classification.py           
          
      - name: Reports
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            cat reports.txt >> results.md
            echo >> results.md
            cml-publish confusion_matrix.png --md --title 'confusion-matrix' >> results.md
            cml-publish accuracy_loss.png --md --title 'accuracy_loss' >> results.md
            cml-send-comment results.md

